export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER';
export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CHANGE_PROFILE_PHOTO = 'CHANGE_PROFILE_PHOTO';
export const CHANGE_PROFILE_PASSWORD = 'CHANGE_PROFILE_PASSWORD';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_ADMINISTRATOR = 'UPDATE_ADMINISTRATOR';
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';

export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const BLOCK_CUSTOMER = 'BLOCK_CUSTOMER';
export const UNBLOCK_CUSTOMER = 'UNBLOCK_CUSTOMER';

export const CREATE_BOOK = 'CREATE_BOOK';
export const FETCH_BOOK = 'FETCH_BOOK';

export const UPDATE_BOOK = 'UPDATE_BOOK';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_MARK = 'CREATE_MARK';
export const APPROVE_COMMENT = 'APPROVE_COMMENT';
export const DECLINE_COMMENT = 'DECLINE_COMMENT';

export const FETCH_BOOK_BY_CATEGORY = 'FETCH_BOOK_BY_CATEGORY';

export const FETCH_SHOPPING_CART = 'FETCH_SHOPPING_CART';
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART';
export const DELETE_FROM_SHOPPING_CART = 'DELETE_FROM_SHOPPING_CART';

export const FETCH_CITIES = 'FETCH_CITIES';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const CREATE_CITY = 'CREATE_CITY';

export const FETCH_ORDERS_BY_CUSTOMER = 'FETCH_ORDERS_BY_CUSTOMER';

export const CREATE_ORDER = 'CREATE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const APPROVE_ORDER = 'APPROVE_ORDER';
export const DECLINE_ORDER = 'DECLINE_ORDER';
