export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS';
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER';
export const FETCH_AUTHORS = 'FETCH_AUTHORS';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CHANGE_PROFILE_PHOTO = 'CHANGE_PROFILE_PHOTO';
export const CHANGE_PROFILE_PASSWORD = 'CHANGE_PROFILE_PASSWORD';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const UPDATE_ADMINISTRATOR = 'UPDATE_ADMINISTRATOR';
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const FETCH_LANGUAGE = 'FETCH_LANGUAGE';

export const CREATE_LANGUAGE = 'CREATE_LANGUAGE';
export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE';

export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const BLOCK_CUSTOMER = 'BLOCK_CUSTOMER';
export const UNBLOCK_CUSTOMER = 'UNBLOCK_CUSTOMER';
